sonar.organization=rojasmarquezmanuelmateo-prog
sonar.projectKey=rojasmarquezmanuelmateo-prog_App-seminario-mach

sonar.sources=.
sonar.exclusions=venv/**,tests/**

sonar.tests=tests
sonar.python.coverage.reportPaths=coverage.xml
